<?php

namespace AppBundle\Repository;

/**
 * SuburbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuburbRepository extends \Doctrine\ORM\EntityRepository
{
}
